vim.fn.sign_define("DapBreakpoint", { text = "✋", texthl = "", linehl = "", numhl = "" })
vim.fn.sign_define("DapStopped", { text = "▶", texthl = "", linehl = "", numhl = "" })
vim.keymap.set("n", "<leader>dc", require("dap").continue)
vim.keymap.set("n", "<F5>", require("dap").restart)
vim.keymap.set("n", "<F9>", require("dap").step_over)
vim.keymap.set("n", "<F10>", require("dap").step_into)
vim.keymap.set("n", "<F11>", require("dap").step_out)
vim.keymap.set("n", "<F12>", require("dap").step_back)
vim.keymap.set("n", "<C-b>", require("dap").toggle_breakpoint, { desc = "toggle breakpoint", noremap = true, silent = true })
